# Generated by Django 5.1.1 on 2024-09-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_friendrequest_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('sender', 'receiver')},
        ),
    ]
