# Generated by Django 5.1.1 on 2024-09-18 07:23

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_friendrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
