# Generated by Django 5.1.1 on 2024-09-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
