# Generated by Django 5.1.1 on 2024-09-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_profile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
